# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(email: 'cokr3430@gmail.com', password: "12341234", password_confirmation: "12341234")

## backup
Voca.create(user_id: 1, word: "alternate", meaning: "a. 다른, 대신의 | 번갈아 나오는, 교대의", step: 3, day: 1)
Voca.create(user_id: 1, word: "ascertain", meaning: "v. 확인하다", step: 4, day: 1)
Voca.create(user_id: 1, word: "borrow", meaning: "v. 빌리다", step: 3, day: 1)
Voca.create(user_id: 1, word: "bound", meaning: "a. ~행의 | 꼭 ~하게 되어 있는", step: 4, day: 1)
Voca.create(user_id: 1, word: "commute", meaning: "v. 통근하다 | n. 출퇴근, 통근", step: 3, day: 1)
Voca.create(user_id: 1, word: "convoluted", meaning: "a. 복잡한, 뒤얽힌", step: 4, day: 1)
Voca.create(user_id: 1, word: cramped, meaning: a. 비좁은, 갑갑한, step: 3, day: 1)
Voca.create(user_id: 1, word: curb, meaning: n. (인도와 차도 사이의) 도로 경계석 | v. 억제하다, 구속하다, step: 3, day: 1)
Voca.create(user_id: 1, word: descent, meaning: n. 하강 | 혈통, 가계, step: 3, day: 1)
Voca.create(user_id: 1, word: designate, meaning: v. 지정하다, step: 3, day: 1)
Voca.create(user_id: 1, word: destination, meaning: n. 목적지, 행선지, step: 3, day: 1)
Voca.create(user_id: 1, word: detour, meaning: n. 우회, 우회 도로, step: 3, day: 1)
Voca.create(user_id: 1, word: deviate, meaning: v. 벗어나다, 빗나가다, step: 2, day: 1)
Voca.create(user_id: 1, word: direction, meaning: n. 방향, step: 3, day: 1)
Voca.create(user_id: 1, word: drive under the influence, meaning: phr. 음주 운전하다, step: 3, day: 1)
Voca.create(user_id: 1, word: drop off, meaning: phr. ~를 (차에서) 내려 주다, step: 3, day: 1)
Voca.create(user_id: 1, word: fare, meaning: n. (기차, 버스, 택시의) 요금, 운임, step: 4, day: 1)
Voca.create(user_id: 1, word: fine, meaning: n. 벌금, 과태료 | v. ~에게 벌금을 부과하다 | a. 아주 작은, step: 3, day: 1)
Voca.create(user_id: 1, word: hail, meaning: v. 불러 세우다 | 환호하여 맞이하다, step: 3, day: 1)
Voca.create(user_id: 1, word: impassable, meaning: a. 지나갈 수 없는, step: 4, day: 1)
Voca.create(user_id: 1, word: interrupt, meaning: v. 가로막다, 저지하다, step: 3, day: 1)
Voca.create(user_id: 1, word: jam, meaning: v. (장소, 통로를) 막다, 메우다, step: 3, day: 1)
Voca.create(user_id: 1, word: jaywalk, meaning: v. 길을 무단 횡단하다, step: 3, day: 1)
Voca.create(user_id: 1, word: jump the gun, meaning: phr. 성급하게 출발하다, 성급하게 행동하다, step: 4, day: 1)
Voca.create(user_id: 1, word: locate, meaning: v. 위치시키다 | 찾아내다, step: 3, day: 1)
Voca.create(user_id: 1, word: mileage, meaning: n. 연비, step: 4, day: 1)
Voca.create(user_id: 1, word: mount, meaning: v. 설치하다 | 늘다, step: 3, day: 1)
Voca.create(user_id: 1, word: navigate, meaning: v. 항해하다, 비행하다, step: 4, day: 1)
Voca.create(user_id: 1, word: notice, meaning: v. 알아차리다, step: 4, day: 1)
Voca.create(user_id: 1, word: opposite, meaning: a. 반대의, 반대편의, step: 3, day: 1)
Voca.create(user_id: 1, word: pick up, meaning: phr. ~를 태워주다, ~를 데리러 가다 | 회복하다 | ~을 익히다, step: 4, day: 1)
Voca.create(user_id: 1, word: pull over, meaning: phr. (차를) 길가에 대다, step: 2, day: 1)
Voca.create(user_id: 1, word: recommend, meaning: v. 추천하다, step: 4, day: 1)
Voca.create(user_id: 1, word: related, meaning: a. 관련된, step: 3, day: 1)
Voca.create(user_id: 1, word: route, meaning: n. 길, 노선, step: 4, day: 1)
Voca.create(user_id: 1, word: stop by, meaning: phr. 잠깐 들르다, step: 4, day: 1)
Voca.create(user_id: 1, word: transfer, meaning: v. 갈아타다 | 전근하다, 전학하다 | (전화로) 연결해 주다, step: 4, day: 1)
Voca.create(user_id: 1, word: transport, meaning: v. 수송하다, 운송하다, step: 3, day: 1)
Voca.create(user_id: 1, word: validate, meaning: v. 확인하다, 증명하다, step: 3, day: 1)
Voca.create(user_id: 1, word: veer, meaning: v. 방향을 바꾸다, step: 4, day: 1)
Voca.create(user_id: 1, word: abundant, meaning: a. 풍부한, step: 4, day: 2)
Voca.create(user_id: 1, word: account, meaning: n. 계좌, step: 4, day: 2)
Voca.create(user_id: 1, word: appraise, meaning: v. (가치, 가격을) 감정하다, 평가하다, step: 4, day: 2)
Voca.create(user_id: 1, word: bilk, meaning: v. ~에게 사기치다, ~를 속여 빼앗다, step: 4, day: 2)
Voca.create(user_id: 1, word: budget, meaning: n. 예산, step: 3, day: 2)
Voca.create(user_id: 1, word: commodity, meaning: n. 상품, 일용품, step: 3, day: 2)
Voca.create(user_id: 1, word: compensate, meaning: v. ~에게 보상하다 | 보충하다, step: 4, day: 2)
Voca.create(user_id: 1, word: consolidate, meaning: v. (회사, 재산 등을) 통합하다, 합병하다, step: 4, day: 2)
Voca.create(user_id: 1, word: crisis, meaning: n. 위기, step: 3, day: 2)
Voca.create(user_id: 1, word: currency, meaning: n. 화폐, 통화, step: 3, day: 2)
Voca.create(user_id: 1, word: cut down on, meaning: phr. (비용, 수량을) 줄이다, step: 4, day: 2)
Voca.create(user_id: 1, word: deficit, meaning: n. 적자 | 부족, 부족액, step: 3, day: 2)
Voca.create(user_id: 1, word: demand, meaning: n. 수요 | v. 요구하다, step: 4, day: 2)
Voca.create(user_id: 1, word: deposit, meaning: v. (은행에) 예금하다 | 퇴적시키다 | n. 보증금, 계약금, step: 3, day: 2)
Voca.create(user_id: 1, word: disparity, meaning: n. 격차, 불일치, step: 4, day: 2)
Voca.create(user_id: 1, word: downturn, meaning: n. (경기의) 침체, 하락, step: 4, day: 2)
Voca.create(user_id: 1, word: dwindle, meaning: v. 줄어들다, 점차 감소하다, step: 4, day: 2)
Voca.create(user_id: 1, word: eliminate, meaning: v. 없애다, 제거하다, step: 4, day: 2)
Voca.create(user_id: 1, word: endow, meaning: v. 기부하다, step: 1, day: 2)
Voca.create(user_id: 1, word: ensure, meaning: v. 보장하다, 보증하다, step: 3, day: 2)
Voca.create(user_id: 1, word: frugal, meaning: a. 절약하는, step: 3, day: 2)
Voca.create(user_id: 1, word: fund, meaning: v. (사업 등)에 자금을 대다, step: 4, day: 2)
Voca.create(user_id: 1, word: in the red, meaning: a. 적자인, step: 4, day: 2)
Voca.create(user_id: 1, word: investment, meaning: n. 투자, step: 3, day: 2)
Voca.create(user_id: 1, word: liability, meaning: n. (-ies) 부채, 빚 | 의무, 책임, step: 3, day: 2)
Voca.create(user_id: 1, word: loan, meaning: n. 대출, 대부금, step: 3, day: 2)
Voca.create(user_id: 1, word: mortgage, meaning: n. 주택 담보 대출 | v. (토지, 재산을) 저당 잡히다, step: 3, day: 2)
Voca.create(user_id: 1, word: mutable, meaning: a. 변하기 쉬운, step: 3, day: 2)
Voca.create(user_id: 1, word: persistent, meaning: a. 게속되는 | 집요한, 완고한, step: 3, day: 2)
Voca.create(user_id: 1, word: plummet, meaning: v. (가격, 물가가) 폭락하다, step: 4, day: 2)
Voca.create(user_id: 1, word: plunge, meaning: v. 떨어지다, 급락하다 | 뛰어들다, step: 4, day: 2)
Voca.create(user_id: 1, word: property, meaning: n. 부동산, 재산 | 특징, step: 4, day: 2)
Voca.create(user_id: 1, word: prospect, meaning: n. 전망, 가능성, step: 4, day: 2)
Voca.create(user_id: 1, word: recession, meaning: n. 불경기, 경기 침체, step: 3, day: 2)
Voca.create(user_id: 1, word: redeem, meaning: v. (쿠폰 등을) 상품, 현금으로 바꾸다, step: 3, day: 2)
Voca.create(user_id: 1, word: reimburse, meaning: v. 변제하다, 상환하다, step: 1, day: 2)
Voca.create(user_id: 1, word: remuneration, meaning: n. 보수, 보상, step: 3, day: 2)
Voca.create(user_id: 1, word: risky, meaning: a. 위험한, 아슬아슬한, step: 3, day: 2)
Voca.create(user_id: 1, word: skyrocket, meaning: v. 급상승하다, step: 4, day: 2)
Voca.create(user_id: 1, word: soar, meaning: v. 치솟다, 급상승하다, step: 3, day: 2)
Voca.create(user_id: 1, word: statement, meaning: n. 명세서 | 성명, 진술, step: 3, day: 2)
Voca.create(user_id: 1, word: stimulate, meaning: v. 자극하다, 북돋우다, step: 3, day: 2)
Voca.create(user_id: 1, word: stock, meaning: n. 주식 | 재고 | v. 저장하다, 비축하다, step: 4, day: 2)
Voca.create(user_id: 1, word: subsidy, meaning: n. 보조금, step: 4, day: 2)
Voca.create(user_id: 1, word: sustain, meaning: v. 유지하다, 지탱하다, step: 3, day: 2)
Voca.create(user_id: 1, word: tally, meaning: v. 계산하다, step: 3, day: 2)
Voca.create(user_id: 1, word: withdrawal, meaning: n. 인출, step: 4, day: 2)
Voca.create(user_id: 1, word: appeal, meaning: v. 마음에 들다, 매력이 있다 | 간청하다 | n. 매력, step: 2, day: 3)
Voca.create(user_id: 1, word: artificial, meaning: a. 인공적인 | 부자연스러운, step: 2, day: 3)
Voca.create(user_id: 1, word: authentic, meaning: a. 진정한, 진짜의 | 믿을 만한, 확실한, step: 2, day: 3)
Voca.create(user_id: 1, word: balance, meaning: n. 균형, 조화 | 잔고 | v. ~의 균형을 유지하다, step: 2, day: 3)
Voca.create(user_id: 1, word: bland, meaning: a. (맛이) 싱거운, 담백한, step: 2, day: 3)
Voca.create(user_id: 1, word: brew, meaning: v. (차 등을) 끓이다, step: 2, day: 3)
Voca.create(user_id: 1, word: cater, meaning: v. (연회 등에) 음식을 출장 제공하다 | ~의 요구에 응하다, step: 2, day: 3)
Voca.create(user_id: 1, word: complement, meaning: v. 보완하다, 보충하다, step: 2, day: 3)
Voca.create(user_id: 1, word: consumption, meaning: n. 소비, 소비량, step: 2, day: 3)
Voca.create(user_id: 1, word: contain, meaning: v. 담고 있다, 포함하다, step: 2, day: 3)
Voca.create(user_id: 1, word: craving, meaning: n. (강렬한) 욕구, 갈망, step: 2, day: 3)
Voca.create(user_id: 1, word: dairy, meaning: a. 유제품의, 우유의, step: 2, day: 3)
Voca.create(user_id: 1, word: detract, meaning: v. (가치, 명성 등을) 떨어뜨리다, 손상시키다, step: 2, day: 3)
Voca.create(user_id: 1, word: edible, meaning: a. 먹을 수 있는, step: 2, day: 3)
Voca.create(user_id: 1, word: essential, meaning: a. 필수의, 없어서는 안 될 | n. 필수품, step: 2, day: 3)
Voca.create(user_id: 1, word: feel free to, meaning: phr. 마음대로 ~하다, step: 2, day: 3)
Voca.create(user_id: 1, word: grab a bite, meaning: phr. 간단히 먹다, step: 2, day: 3)
Voca.create(user_id: 1, word: greasy, meaning: a. (음식이) 기름진, step: 2, day: 3)
Voca.create(user_id: 1, word: help oneself to, meaning: phr. ~을 마음껏 먹다, step: 2, day: 3)
Voca.create(user_id: 1, word: hit the spot, meaning: phr. 만족스럽다, step: 2, day: 3)
Voca.create(user_id: 1, word: ingredient, meaning: n. 재료, 성분, step: 2, day: 3)
Voca.create(user_id: 1, word: invitation, meaning: n. 초대, 초대장, step: 2, day: 3)
Voca.create(user_id: 1, word: make up one's mind, meaning: phr. 결정하다, 결심하다, step: 2, day: 3)
Voca.create(user_id: 1, word: minimum, meaning: a. 최소의, 최저의 | n. 최소, 최저, step: 2, day: 3)
Voca.create(user_id: 1, word: mixture, meaning: n. 혼합물, step: 2, day: 3)
Voca.create(user_id: 1, word: nutrient, meaning: n. 영양소, 영양분, step: 2, day: 3)
Voca.create(user_id: 1, word: order, meaning: n. 주문 | 질서 | v. 명령하다, step: 2, day: 3)
Voca.create(user_id: 1, word: parched, meaning: a. 목타는, step: 2, day: 3)
Voca.create(user_id: 1, word: picky, meaning: a. 까다로운, step: 2, day: 3)
Voca.create(user_id: 1, word: preserve, meaning: v. 저장하다 | 보존하다, 유지하다, step: 2, day: 3)
Voca.create(user_id: 1, word: provision, meaning: n. (-s) 식량 | (법률) 조항, 규정 | 공급, step: 2, day: 3)
Voca.create(user_id: 1, word: recipe, meaning: n. 조리법, step: 2, day: 3)
Voca.create(user_id: 1, word: refined, meaning: a. 세련된, 품위 있는, step: 2, day: 3)
Voca.create(user_id: 1, word: rigorous, meaning: a. 엄격한, 혹독한, step: 2, day: 3)
Voca.create(user_id: 1, word: savor, meaning: v. 음미하다, 맛보다, step: 2, day: 3)
Voca.create(user_id: 1, word: serve, meaning: v. (음식을) 내다, 시중들다 | 역할을 하다, step: 2, day: 3)
Voca.create(user_id: 1, word: set out, meaning: phr. 시작하다, 착수하다, step: 2, day: 3)
Voca.create(user_id: 1, word: speechless, meaning: a. (충격으로) 말문이 막힌, step: 2, day: 3)
Voca.create(user_id: 1, word: spill, meaning: v. 엎지르다 | n. 유출, step: 2, day: 3)
Voca.create(user_id: 1, word: split the bill, meaning: phr. 비용을 각자 부담하다, step: 2, day: 3)
Voca.create(user_id: 1, word: staple, meaning: n. 주식, step: 2, day: 3)
Voca.create(user_id: 1, word: sufficient, meaning: a. 충분한, step: 2, day: 3)
Voca.create(user_id: 1, word: tenderize, meaning: v. (고기 등을) 연하게 하다, step: 2, day: 3)
Voca.create(user_id: 1, word: treat, meaning: n. 한턱내기 | v. 대우하다, 다루다 | 치료하다, step: 2, day: 3)
Voca.create(user_id: 1, word: vegetarian, meaning: n. 채식주의자, step: 2, day: 3)
Voca.create(user_id: 1, word: voracious, meaning: a. 식욕이 왕성한, step: 2, day: 3)
Voca.create(user_id: 1, word: account for, meaning: phr. ~을 설명하다 | (~의 비율을) 차지하다, step: 1, day: 4)
Voca.create(user_id: 1, word: adaptation, meaning: n. 각색 작품 | 적응, step: 1, day: 4)
Voca.create(user_id: 1, word: anonymous, meaning: a. 익명의, 작자 불명의, step: 1, day: 4)
Voca.create(user_id: 1, word: banality, meaning: n. 진부함, 진부한 말, step: 1, day: 4)
Voca.create(user_id: 1, word: bilingual, meaning: a. 두 나라 말을 하는, step: 1, day: 4)
Voca.create(user_id: 1, word: coin, meaning: v. (새로운 말을) 만들어내다, step: 1, day: 4)
Voca.create(user_id: 1, word: comment, meaning: n. 의견, 논평 | v. 언급하다, 논평하다, step: 1, day: 4)
Voca.create(user_id: 1, word: complex, meaning: a. 복잡한, step: 1, day: 4)
Voca.create(user_id: 1, word: connotation, meaning: n. 함축, 암시, step: 1, day: 4)
Voca.create(user_id: 1, word: copy, meaning: n. (같은 책, 잡지의) 부 | 사본, step: 1, day: 4)
Voca.create(user_id: 1, word: critic, meaning: n. 비평가, 평론가, step: 1, day: 4)
Voca.create(user_id: 1, word: decipher, meaning: v. (문자, 암호를) 해독하다, 판독하다, step: 1, day: 4)
Voca.create(user_id: 1, word: deduce, meaning: v. 추론하다, step: 1, day: 4)
Voca.create(user_id: 1, word: draft, meaning: n. 초고, 초안 | 외풍, step: 1, day: 4)
Voca.create(user_id: 1, word: edition, meaning: n. (간행물의) 판, step: 1, day: 4)
Voca.create(user_id: 1, word: emphasize, meaning: v. 강조하다, step: 1, day: 4)
Voca.create(user_id: 1, word: engrossing, meaning: a. 마음을 사로잡는, step: 1, day: 4)
Voca.create(user_id: 1, word: exaggerate, meaning: v. 과장하다, step: 1, day: 4)
Voca.create(user_id: 1, word: fathom, meaning: v. 이해하다, 헤아리다, step: 1, day: 4)
Voca.create(user_id: 1, word: gist, meaning: n. 요점, 요지, step: 1, day: 4)
Voca.create(user_id: 1, word: implication, meaning: n. 함축적 의미, 암시, step: 1, day: 4)
Voca.create(user_id: 1, word: induce, meaning: v. 일으키다, 야기하다, step: 1, day: 4)
Voca.create(user_id: 1, word: interpret, meaning: v. (외국어를) 통역하다 | 해석하다, step: 1, day: 4)
Voca.create(user_id: 1, word: ironic, meaning: a. 반어적인, step: 1, day: 4)
Voca.create(user_id: 1, word: legible, meaning: a. (필적, 인쇄가) 읽기 쉬운, step: 1, day: 4)
Voca.create(user_id: 1, word: literary, meaning: a. 문학의, step: 1, day: 4)
Voca.create(user_id: 1, word: manipulate, meaning: v. 솜씨 있게 다루다 | 조작하다, step: 1, day: 4)
Voca.create(user_id: 1, word: mordant, meaning: a. 신랄한, 통렬한, step: 1, day: 4)
Voca.create(user_id: 1, word: myth, meaning: n. 신화, 허구, step: 1, day: 4)
Voca.create(user_id: 1, word: narrative, meaning: n. 이야기, 서술 | a. 서술적인, step: 1, day: 4)
Voca.create(user_id: 1, word: notion, meaning: n. 관념, 개념, step: 1, day: 4)
Voca.create(user_id: 1, word: obfuscate, meaning: v. (판단, 논점 등을) 흐리게 하다, step: 1, day: 4)
Voca.create(user_id: 1, word: obscure, meaning: a. 분명하지 않은, 애매한 | v. 흐리게 하다, step: 1, day: 4)
Voca.create(user_id: 1, word: plot, meaning: n. 줄거리, step: 1, day: 4)
Voca.create(user_id: 1, word: prolific, meaning: a. (작가 등이) 다작의, step: 1, day: 4)
Voca.create(user_id: 1, word: pronounce, meaning: v. 발음하다 | 단언하다, 선언하다, step: 1, day: 4)
Voca.create(user_id: 1, word: prose, meaning: n. 산문, 산문체, step: 1, day: 4)
Voca.create(user_id: 1, word: quirk, meaning: n. 기벽, 이상한 버릇, step: 1, day: 4)
Voca.create(user_id: 1, word: refer to, meaning: v. ~을 언급하다 | ~을 참조하다, step: 1, day: 4)
Voca.create(user_id: 1, word: reminiscence, meaning: n. 추억, 회상, step: 1, day: 4)
Voca.create(user_id: 1, word: simultaneous, meaning: a. 동시의, 동시에 일어나는, step: 1, day: 4)
Voca.create(user_id: 1, word: support, meaning: n. 도움, 지원 | v. 지원하다, 지지하다, step: 1, day: 4)
Voca.create(user_id: 1, word: term, meaning: n. 용어, 표현 | 임기, 기간 | v. 이름 짓다, 칭하다, step: 1, day: 4)
Voca.create(user_id: 1, word: translate, meaning: v. 번역하다, step: 1, day: 4)
Voca.create(user_id: 1, word: vague, meaning: a. 애매한, 막연한, step: 1, day: 4)
Voca.create(user_id: 1, word: verse, meaning: n. 시구, 운문 | (노래의) 구절, step: 1, day: 4)
Voca.create(user_id: 1, word: version, meaning: n. (책 등의) 판 | 번역본, step: 1, day: 4)
